* Support singlemaster in ucs-school-join-secondary-samba4 (Bug #32187) * Fix returncode passing
git-svn-id: svn+ssh://billy.knut.univention.de/var/univention/svn/dev/branches/ucs-3.2/ucs-school-3.2r2@50545 1b283449-9f2f-0410-b571-8eb228e1a901

diff --git a/ucs-school-import/ucs-school-join-secondary-samba4 b/ucs-school-import/ucs-school-join-secondary-samba4
--- a/ucs-school-import/ucs-school-join-secondary-samba4
+++ b/ucs-school-import/ucs-school-join-secondary-samba4
@@ -61,15 +61,15 @@ USERTMP="$(mktemp -d)"
 DCPWD="$USERTMP/dcpwd"
 ROOTPWD="$USERTMP/rootpwd"
 JOIN_LOGFILE="/var/log/univention/join-secondary-samba4.log"
+set -o pipefail
 
 trapOnExit() {
 	rm -rf "$USERTMP"
 	echo "$(LC_ALL=C date): finish $0" >>"$JOIN_LOGFILE" 2>&1
+	exit "$rc"
 }
 
 trap trapOnExit EXIT
-
-{	## start logging
 
 echo "$(LC_ALL=C date): starting $0 $*" >>"$JOIN_LOGFILE" 2>&1
 
@@ -114,11 +114,6 @@ if [ -z "$target_school_dc_ip" ]; then
 	exit 1
 fi
 
-# if ! ldapsearch -xLLL -h "$target_school_dc_ip" -p 7389 -s base -b "$ldap_base" -D "$ldap_hostdn" -y /etc/machine.secret >/dev/null 2>&1; then
-# 	echo "The DC Slave needs to be joined first without Samba4 or UCS@school installed"
-# 	exit 1
-# fi
-
 test_school_role=$(univention-ldapsearch -xLLL "(univentionService=UCS@school)" -b "$ldap_hostdn" -s base dn 2>/dev/null | ldapsearch-wrapper | ldapsearch-decode64  | sed -n 's/^dn: //p')
 
 if [ -n "$test_school_role" ]; then
@@ -152,13 +147,23 @@ if [ ! -f "$ROOTPWD" ]; then
 	echo ""
 fi
 
+{	## start logging
+
 echo -n "Trying ssh access too root@$target_school_dc_ip : "
-if ! test_output=$(univention-ssh "$ROOTPWD" root@"$target_school_dc_ip" /usr/sbin/ucr get ldap/hostdn); then
-	echo "ssh access to root@$target_school_dc_ip failed"
+if ! target_school_dc_server_role=$(univention-ssh "$ROOTPWD" root@"$target_school_dc_ip" /usr/sbin/ucr get server/role); then
+	echo -e "\033[60Gfailed"
 	exit 1
 else
-	echo -e "\033[60Gdone"
+	if [ "$target_school_dc_server_role" = "domaincontroller_slave" ] \
+		|| [ "$target_school_dc_server_role" = "domaincontroller_master" ]; then
+		echo -e "\033[60Gdone"
+	else
+		echo -e "\033[60Gfailed"
+		echo "The server $target_school_dc_ip has an invalid role: '$target_school_dc_server_role'"
+		exit 1
+	fi
 fi
+
 
 echo -n "Search LDAP binddn : "
 binddn="$(univention-ssh "$ROOTPWD" "root@${target_school_dc_ip}" \
@@ -174,7 +179,7 @@ fi
 
 echo -n "Search school server binddn : "
 target_server_udm_output=$(univention-ssh "$ROOTPWD" "root@${target_school_dc_ip}" \
-	/usr/sbin/udm computers/domaincontroller_slave list --filter "\'(&(service=UCS@school)(service=S4 Connector)(ip=$target_school_dc_ip))\'")
+	/usr/sbin/udm "computers/$target_school_dc_server_role" list --filter "\'(&(service=UCS@school)(service=S4 Connector)(ip=$target_school_dc_ip))\'")
 target_school_dc_hostdn=$(echo "$target_server_udm_output" | sed -n 's/^DN: //p')
 target_school_dc_name=$(echo "$target_server_udm_output" | sed -n 's/^ *name: //p')
 if [ -z "$target_school_dc_hostdn" ]; then
@@ -207,65 +212,67 @@ else
 	echo -e "\033[60G$target_server_ucsschool_service"
 fi
 
-echo -n "Determine school OU of school server : "	## check with given Admin credentials, to verify them
-target_school_ou=$(univention-ssh "$DCPWD" "${DCACCOUNT}@${target_school_dc_ip}" \
-	". /usr/share/ucs-school-lib/base.sh; school_ou '$target_school_dc_hostdn'")
+if [ "$target_school_dc_server_role" = "domaincontroller_slave" ]; then
+	echo -n "Determine school OU of school server : "	## check with given Admin credentials, to verify them
+	target_school_ou=$(univention-ssh "$DCPWD" "${DCACCOUNT}@${target_school_dc_ip}" \
+		". /usr/share/ucs-school-lib/base.sh; school_ou '$target_school_dc_hostdn'")
 
-if [ -z "$target_school_ou" ]; then
-	echo -e "\033[60Gfailed"
-	echo "ERROR: Could not determine school OU of the remote school DC."
-	exit 1
-else
-	echo -e "\033[60G$target_school_ou"
-fi
+	if [ -z "$target_school_ou" ]; then
+		echo -e "\033[60Gfailed"
+		echo "ERROR: Could not determine school OU of the remote school DC."
+		exit 1
+	else
+		echo -e "\033[60G$target_school_ou"
+	fi
 
-echo -n "Verify LDAP hostdn : "
-target_ldap_hostdn="$(univention-ssh "$ROOTPWD" "root@${target_school_dc_ip}" \
-	/usr/sbin/udm "computers/$server_role" list --filter name="$hostname" --logfile /dev/null | sed -ne 's|^DN: ||p')"
-if [ -z "$target_ldap_hostdn" ]; then
-	echo -e "\033[60Gfailed"
-	echo "Could not verify ldap/hostdn for local DC."
-	echo "First the host account $hostname needs to be moved to the school OU it should join to."
-	exit 1
-else
-	echo -e "\033[60Gdone"
-fi
+	echo -n "Verify LDAP hostdn : "
+	target_ldap_hostdn="$(univention-ssh "$ROOTPWD" "root@${target_school_dc_ip}" \
+		/usr/sbin/udm computers/domaincontroller_slave list --filter name="$hostname" --logfile /dev/null | sed -ne 's|^DN: ||p')"
+	if [ -z "$target_ldap_hostdn" ]; then
+		echo -e "\033[60Gfailed"
+		echo "Could not verify ldap/hostdn for local DC."
+		echo "First the host account $hostname needs to be moved to the school OU it should join to."
+		exit 1
+	else
+		echo -e "\033[60Gdone"
+	fi
 
-echo -n "Search school OU : "	## check with given Admin credentials, to verify them
-my_school_ou=$(univention-ssh "$DCPWD" "${DCACCOUNT}@${target_school_dc_ip}" \
-	". /usr/share/ucs-school-lib/base.sh; school_ou '$target_ldap_hostdn'")
+	echo -n "Search school OU : "	## check with given Admin credentials, to verify them
+	my_school_ou=$(univention-ssh "$DCPWD" "${DCACCOUNT}@${target_school_dc_ip}" \
+		". /usr/share/ucs-school-lib/base.sh; school_ou '$target_ldap_hostdn'")
 
-if [ -z "$my_school_ou" ]; then
-	echo -e "\033[60Gfailed"
-	echo "Could not determine school OU for local DC."
-	echo "First the host account $hostname needs to be moved to the school OU it should join to."
-	exit 1
-else
-	echo -e "\033[60G$my_school_ou"
-fi
+	if [ -z "$my_school_ou" ]; then
+		echo -e "\033[60Gfailed"
+		echo "Could not determine school OU for local DC."
+		echo "First the host account $hostname needs to be moved to the school OU it should join to."
+		exit 1
+	else
+		echo -e "\033[60G$my_school_ou"
+	fi
 
-if [ "$target_school_ou" != "$my_school_ou" ]; then
-	echo "ERROR: The account of this server $hostname is located below $my_school_ou"
-	echo "        but the server $target_school_dc_ip is in $target_school_ou."
-	exit 1
-fi
+	if [ "$target_school_ou" != "$my_school_ou" ]; then
+		echo "ERROR: The account of this server $hostname is located below $my_school_ou"
+		echo "        but the server $target_school_dc_ip is in $target_school_ou."
+		exit 1
+	fi
 
-echo -n "Check group memberschip : "
-test_output=$(univention-ssh "$ROOTPWD" "root@${target_school_dc_ip}" \
-	/usr/sbin/udm groups/group list --filter name="DC-$target_server_ucsschool_type" | sed -n "/^ *hosts: $target_ldap_hostdn$/p")
-if [ -z "$test_output" ]; then
-	echo -e "\033[60Gfailed"
-	echo "$hostname is not member of the group DC-$target_server_ucsschool_type, this needs to be fixed first manually."
-	exit 1
-fi
-test_output=$(univention-ssh "$ROOTPWD" "root@${target_school_dc_ip}" \
-	/usr/sbin/udm groups/group list --filter name="OU$my_school_ou-DC-$target_server_ucsschool_type" | sed -n "/^ *hosts: $target_ldap_hostdn$/p")
-if [ -z "$test_output" ]; then
-	echo -e "\033[60Gfailed"
-	echo "$hostname is not member of the group OU$my_school_ou-DC-$target_server_ucsschool_type, this needs to be fixed first manually."
-	exit 1
-else
-	echo -e "\033[60Gdone"
+	echo -n "Check group memberschip : "
+	test_output=$(univention-ssh "$ROOTPWD" "root@${target_school_dc_ip}" \
+		/usr/sbin/udm groups/group list --filter name="DC-$target_server_ucsschool_type" | sed -n "/^ *hosts: $target_ldap_hostdn$/p")
+	if [ -z "$test_output" ]; then
+		echo -e "\033[60Gfailed"
+		echo "$hostname is not member of the group DC-$target_server_ucsschool_type, this needs to be fixed first manually."
+		exit 1
+	fi
+	test_output=$(univention-ssh "$ROOTPWD" "root@${target_school_dc_ip}" \
+		/usr/sbin/udm groups/group list --filter name="OU$my_school_ou-DC-$target_server_ucsschool_type" | sed -n "/^ *hosts: $target_ldap_hostdn$/p")
+	if [ -z "$test_output" ]; then
+		echo -e "\033[60Gfailed"
+		echo "$hostname is not member of the group OU$my_school_ou-DC-$target_server_ucsschool_type, this needs to be fixed first manually."
+		exit 1
+	else
+		echo -e "\033[60Gdone"
+	fi
 fi
 
 echo "$(LC_ALL=C date): $0 pre-checks done" >>"$JOIN_LOGFILE" 2>&1
@@ -524,4 +531,13 @@ univention-run-join-scripts -dcaccount "$DCACCOUNT" -dcpwd "$DCPWD" --force --ru
 
 ucs_addServiceToLocalhost "$target_server_ucsschool_service" --binddn "$binddn" --bindpwdfile "$DCPWD"	## required for the ucsschool-s4-branch-site listener
 
+echo
+echo "**************************************************************************"
+univention-check-join-status
+rc=$?
+echo "**************************************************************************"
+echo
+
+exit "$rc"
 } 2>&1 | tee -a "$JOIN_LOGFILE"
+rc=$?	## for trapOnExit
