Bug #35447: update 78_ldap_acls_dump and 78_ldap_acls_dump.diff

diff --git a/ucs-test-ucsschool/90_ucsschool/78_ldap_acls_dump.diff b/ucs-test-ucsschool/90_ucsschool/78_ldap_acls_dump.diff
--- a/ucs-test-ucsschool/90_ucsschool/78_ldap_acls_dump.diff
+++ b/ucs-test-ucsschool/90_ucsschool/78_ldap_acls_dump.diff
@@ -1,22 +1,22 @@
 #!/bin/sh
 
-BASEDIR=$1
+BASEDIR1="$1"
+BASEDIR2="$2"
 
-if [ -z "$1" -o "$1" = "-h" -o "$1" = "--help" ] ; then
-    echo "missing directory argument"
-    echo "example:"
-    echo "  $(basename "$0") /var/log/univention/78_ldap_acls_dump.1489461536.oldconfig"
-    exit 1
+if [ -z "$2" -o -z "$1" -o "$1" = "-h" -o "$1" = "--help" ] ; then
+	echo "missing directory argument"
+	echo "example:"
+	echo "	$(basename "$0") /var/log/univention/78_ldap_acls_dump.1489461536.newconfig /var/log/univention/78_ldap_acls_dump.1489492342.newconfig"
+	exit 1
 fi
 
-for i in ${BASEDIR}/dn*.ldif ; do
-    FN="$(basename "$i")"
-    DIRNAME="$(basename $(basename $(dirname "$i") .oldconfig) .newconfig)"
-	FN_A="/var/log/univention/${DIRNAME}.oldconfig/${FN}"
-	FN_B="/var/log/univention/${DIRNAME}.newconfig/${FN}"
+for i in ${BASEDIR1}/dn*.ldif ; do
+	FN="$(basename "$i")"
+	FN_A="$BASEDIR1/${FN}"
+	FN_B="$BASEDIR2/${FN}"
 	[ ! -f "$FN_A" ] && echo "$FN_A is missing" && continue
 	[ ! -f "$FN_B" ] && echo "$FN_B is missing" && continue
-    (
+	(
 		echo "$FN_A"
 		echo "$FN_B"
 		echo
