Bug #52150: build Docker image without virtualenv

diff --git a/appcenter/inst b/appcenter/inst
--- a/appcenter/inst
+++ b/appcenter/inst
@@ -50,7 +50,7 @@ UDM_CLIENT_UPDATE_SCRIPT="/var/lib/univention-appcenter/apps/$APP_ID/data/update
 
 
 main () {
-    docker exec $appcenter_apps_ucsschool_kelvin_rest_api_container venv/bin/univention-config-registry set \
+    docker exec $appcenter_apps_ucsschool_kelvin_rest_api_container /usr/bin/univention-config-registry set \
     ucsschool/import/set/netlogon/script/path="$(ucr get ucsschool/import/set/netlogon/script/path)" \
     ucsschool/import/set/homedrive="$(ucr get ucsschool/import/set/homedrive)" \
     ucsschool/import/set/sambahome="$(ucr get ucsschool/import/set/sambahome)" \
@@ -61,6 +61,8 @@ main () {
         touch "$TOKEN_SIGN_SECRET_FILE"
         chown root:root "$TOKEN_SIGN_SECRET_FILE"
         chmod 640 "$TOKEN_SIGN_SECRET_FILE"
+        # prevent "unable to write 'random state'" because $HOME is not set
+        export RANDFILE=/.rnd
         openssl rand -hex 32 > "$TOKEN_SIGN_SECRET_FILE" || die
     else
         echo "Using existing token key."
@@ -162,11 +164,17 @@ The "__pycache__" directory can be safely ignored.
 }
 
 check_openapi_client_knows_ucssschool() {
-  if ! univention-app shell "$APP_ID" /kelvin/venv/bin/python3 -c "import sys; from openapi_client_udm import UsersUserOptions; sys.exit(0 if 'ucsschool_administrator' in UsersUserOptions.openapi_types else 1)"; then
+  OPENAPI_TEST_CODE="import sys; from openapi_client_udm import UsersUserOptions; sys.exit(0 if 'ucsschool_administrator' in UsersUserOptions.openapi_types else 1)"
+  if ! univention-app shell "$APP_ID" /usr/bin/python3 -c "$OPENAPI_TEST_CODE"; then
     echo "Building OpenAPI client library in Docker container..."
     univention-app shell "$APP_ID" "$UDM_CLIENT_UPDATE_SCRIPT"
+    if univention-app shell "$APP_ID" /usr/bin/python3 -c "$OPENAPI_TEST_CODE"; then
+      echo "OK: OpenAPI client library now knows UCS@school types."
+    else
+      die "FAIL: OpenAPI client library in Docker container still not usable!"
+    fi
   else
-    echo "OpenAPI client library knows UCS@school types."
+    echo "OK: OpenAPI client library already knows UCS@school types."
   fi
 }
 
