Bug #51828: improve readability of join script

diff --git a/appcenter/inst b/appcenter/inst
--- a/appcenter/inst
+++ b/appcenter/inst
@@ -47,41 +47,58 @@ KELVIN_IMPORTUSER_HOOKS_README="${KELVIN_IMPORTUSER_HOOKS_PATH}/README.txt"
 . /usr/share/univention-join/joinscripthelper.lib || exit 1
 . /usr/share/univention-appcenter/joinscripthelper.sh || exit 1
 
+check_docker_container_is_running() {
+  if ! univention-app status "$APP_ID" >/dev/null; then
+    echo "Docker container of Kelvin API is not running."
+    exit 1
+  fi
+}
 
-main () {
-    docker exec $appcenter_apps_ucsschool_kelvin_rest_api_container venv/bin/univention-config-registry set \
+copy_ucrvs_from_host_to_container() {
+  echo "Copying UCR variables from host to container..."
+  echo "Ignore the following 'E: your request could not be fulfilled' message."
+  univention-app shell "$APP_ID" "$@" /kelvin/venv/bin/univention-config-registry set \
     ucsschool/import/set/netlogon/script/path="$(ucr get ucsschool/import/set/netlogon/script/path)" \
     ucsschool/import/set/homedrive="$(ucr get ucsschool/import/set/homedrive)" \
     ucsschool/import/set/sambahome="$(ucr get ucsschool/import/set/sambahome)" \
     ucsschool/singlemaster="$(ucr get ucsschool/singlemaster)" \
     ucsschool/import/set/serverprofile/path="$(ucr get ucsschool/import/set/serverprofile/path)"
-    if ! [ -e "$TOKEN_SIGN_SECRET_FILE" ]; then
-        echo "Storing token key in $TOKEN_SIGN_SECRET_FILE."
-        touch "$TOKEN_SIGN_SECRET_FILE"
-        chown root:root "$TOKEN_SIGN_SECRET_FILE"
-        chmod 640 "$TOKEN_SIGN_SECRET_FILE"
-        openssl rand -hex 32 > "$TOKEN_SIGN_SECRET_FILE" || die
-    else
-        echo "Using existing token key."
-    fi
+}
 
-    if ! [ -e "$CN_ADMIN_SECRET_FILE" ]; then
-        echo "Storing cn=admin password in $CN_ADMIN_SECRET_FILE."
-        touch "$CN_ADMIN_SECRET_FILE"
-        chown root:root "$CN_ADMIN_SECRET_FILE"
-        chmod 640 "$CN_ADMIN_SECRET_FILE"
-        cat /etc/ldap.secret > "$CN_ADMIN_SECRET_FILE" || die
-    else
-        echo "Using existing password file."
-    fi
+create_tokens_secret_file() {
+  if ! [ -e "$TOKEN_SIGN_SECRET_FILE" ]; then
+    echo "Storing token key in $TOKEN_SIGN_SECRET_FILE."
+    touch "$TOKEN_SIGN_SECRET_FILE"
+    chown root:root "$TOKEN_SIGN_SECRET_FILE"
+    chmod 640 "$TOKEN_SIGN_SECRET_FILE"
+    openssl rand -hex 32 >"$TOKEN_SIGN_SECRET_FILE" || die
+  else
+    echo "Using existing token key."
+  fi
+}
 
-    if ! [ -e "$KELVIN_IMPORT_CONFIG_FILE" ]; then
-      echo "Creating empty config file for the Import Framework used by Kelvin."
-      echo "{}" > "$KELVIN_IMPORT_CONFIG_FILE"
-    fi
+create_cn_admin_secret_file() {
+  if ! [ -e "$CN_ADMIN_SECRET_FILE" ]; then
+    echo "Storing cn=admin password in $CN_ADMIN_SECRET_FILE."
+    touch "$CN_ADMIN_SECRET_FILE"
+    chown root:root "$CN_ADMIN_SECRET_FILE"
+    chmod 640 "$CN_ADMIN_SECRET_FILE"
+    cat /etc/ldap.secret >"$CN_ADMIN_SECRET_FILE" || die
+  else
+    echo "Using existing password file."
+  fi
+}
 
-    if ! [ -e "$KELVIN_IMPORTUSER_HOOKS_README" ]; then
-      echo 'Directory for hooks for the UCS@school Kelvin REST API
+create_empty_import_config_file() {
+  if ! [ -e "$KELVIN_IMPORT_CONFIG_FILE" ]; then
+    echo "Creating empty config file for the Import Framework used by Kelvin."
+    echo "{}" >"$KELVIN_IMPORT_CONFIG_FILE"
+  fi
+}
+
+create_kelvin_hook_readme_file() {
+  if ! [ -e "$KELVIN_IMPORTUSER_HOOKS_README" ]; then
+    echo 'Directory for hooks for the UCS@school Kelvin REST API
 ------------------------------------------------------
 
 The content of this directory is scanned when the Kelvin API
@@ -128,17 +145,20 @@ For example::
         await udm_user_obj.save()  # UDM REST Client object: "save", not "modify"
 
 The "__pycache__" directory can be safely ignored.
-' > "$KELVIN_IMPORTUSER_HOOKS_README"
-    fi
+' >"$KELVIN_IMPORTUSER_HOOKS_README"
+  fi
+}
 
-  echo "Creating group for users that are allowed to connect to the Kelvin API"
-  echo "($ADMIN_GROUP)..."
-	univention-directory-manager groups/group create "$@" --ignore_exists \
-		--position "cn=groups,$ldap_base" \
-		--set name="$ADMIN_GROUP" \
-		--set description="Users that are allowed to connect to the Kelvin API." \
-		--append "users=uid=Administrator,cn=users,$ldap_base" || die
+create_kelvin_access_admin_group() {
+  echo "Creating group for users that are allowed to connect to the Kelvin API ($ADMIN_GROUP)..."
+  univention-directory-manager groups/group create "$@" --ignore_exists \
+    --position "cn=groups,$ldap_base" \
+    --set name="$ADMIN_GROUP" \
+    --set description="Users that are allowed to connect to the Kelvin API." \
+    --append "users=uid=Administrator,cn=users,$ldap_base" || die
+}
 
+create_udm_rest_api_access_group() {
   echo "Creating group '$UDM_REST_GROUP' for machine accounts that are allowed to access the UDM REST API."
   univention-directory-manager groups/group create "$@" --ignore_exists \
     --position "cn=groups,$ldap_base" \
@@ -157,27 +177,34 @@ The "__pycache__" directory can be safely ignored.
 
   echo "Restarting UDM REST API service."
   service univention-directory-manager-rest restart || die
-  sleep 1  # prevent [502] Proxy Error, in case of access before UDM REST API is ready
+  sleep 1 # prevent [502] Proxy Error, in case of access before UDM REST API is ready
 }
 
-check_openapi_client_knows_ucssschool() {
-  if ! univention-app shell "$APP_ID" /kelvin/venv/bin/python3 -c "import sys; from openapi_client_udm import UsersUserOptions; sys.exit(0 if 'ucsschool_administrator' in UsersUserOptions.openapi_types else 1)"; then
+build_openapi_client_library() {
+  if ! univention-app shell "$APP_ID" "$@" /kelvin/venv/bin/python3 -c "import sys; from openapi_client_udm import UsersUserOptions; sys.exit(0 if 'ucsschool_administrator' in UsersUserOptions.openapi_types else 1)"; then
     echo "Building OpenAPI client library in Docker container..."
     MACHINE_USER="$(ucr get appcenter/apps/$APP_ID/hostdn | cut -d ',' -f 1 | cut -d '=' -f 2)\$"
     MACHINE_PASSWORD_FILE="$(docker inspect --format='{{.GraphDriver.Data.MergedDir}}' "$(ucr get appcenter/apps/$APP_ID/container)")/etc/machine.secret"
     MACHINE_PASSWORD="$(<"$MACHINE_PASSWORD_FILE")"
-    univention-app shell "$APP_ID" /bin/sh -c ". /kelvin/venv/bin/activate; update_openapi_client --generator java --jar /kelvin/openapi-generator/jar/openapi-generator-cli-*.jar --insecure --username \"$MACHINE_USER\" --password \"$MACHINE_PASSWORD\" \"\$DOCKER_HOST_NAME\" && /etc/init.d/ucsschool-kelvin-rest-api restart || exit 1"
+    univention-app shell "$APP_ID" "$@" /bin/sh -c ". /kelvin/venv/bin/activate; update_openapi_client --generator java --jar /kelvin/openapi-generator/jar/openapi-generator-cli-*.jar --insecure --username \"$MACHINE_USER\" --password \"$MACHINE_PASSWORD\" \"\$DOCKER_HOST_NAME\" && /etc/init.d/ucsschool-kelvin-rest-api restart || exit 1"
   else
-    echo "OpenAPI client library knows UCS@school types."
+    echo "OK: OpenAPI client library knows UCS@school types."
   fi
 }
 
-
 joinscript_init
+
 eval $(ucr shell ldap/base appcenter/apps/ucsschool-kelvin-rest-api/hostdn appcenter/apps/ucsschool-kelvin-rest-api/container)
 
-main "$@"
-check_openapi_client_knows_ucssschool
+check_docker_container_is_running
+copy_ucrvs_from_host_to_container "$@"
+create_tokens_secret_file
+create_cn_admin_secret_file
+create_empty_import_config_file
+create_kelvin_hook_readme_file
+create_kelvin_access_admin_group "$@"
+create_udm_rest_api_access_group "$@"
+build_openapi_client_library "$@"
 
 joinscript_save_current_version
 exit $?
